### ISSUE TITLE
Feature: SDK's

### ISSUE THREAD

**Issue by fcarvalhido** [zinclabs/zinc#12]
This tool looks promising and it would be great to start planning SDK, so everyone can build tools on top of it.

**Comment by prabhatsharma** [comment]
Agree. I think I will wait for the core APIs to stabilize a bit before embarking on it though.

**Comment by B0bbyD0llar** [comment]
At the moment I'm building a PHP SDK. When it becomes presentable, I would publish it.

**Comment by Sterginsy** [comment]
Omolhs Ng c

**Comment by prabhatsharma** [comment]
We have been thinking about what is the best way to implement this. We have 3 options:

1.  Build SDKs in each language for existing APIs
2. Start using protobuf and generate SDKs from those.
3. Since we have many ES/OS compatible APIs now, use opensearch clients for each language.

**Comment by prabhatsharma** [comment]
Now that swagger specification has been implemented, we could use https://github.com/OpenAPITools/openapi-generator to generate SDKs

**Comment by hengfeiyang** [comment]
We have build three language SDKs use `openapi-generator`:

https://github.com/zinclabs/sdk-go-zincsearch
https://github.com/zinclabs/sdk-nodejs-zincsearch
https://github.com/zinclabs/sdk-python-zincsearch
