### ISSUE TITLE
Log Ingestion via Filebeat Fails

### ISSUE THREAD

**Issue by wrharding** [zinclabs/zinc#123]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want to see in Zinc?
Log ingestion via Filebeat (see #90)

**Which service(s) is this relate to?**
This could be GUI or API
Log ingestion/index creation

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
I am unable to ingest data from Filebeat into Zinc. Specifically, I am trying to ingest syslog and auth.log. Using a modified version of the [Filebeat config](https://docs.zinclabs.io/ingestion/filebeat/) example, I am getting the below error:

```
Mar 27 18:15:17 snail filebeat[19654]: {"log.level":"error","@timestamp":"2022-03-27T18:15:17.202Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":150},"message":"Failed to connect to backoff(elasticsearch(http://127.0.0.1:4080/es/)): Connection marked as failed because the onConnect callback failed: error loading template: failed to load template: couldn't load template: 400 Bad Request: {\"error\":\"error_type: parsing_exception, reason: [mappings] properties [type] should be exists\"}. Response body: {\"error\":\"error_type: parsing_exception, reason: [mappings] properties [type] should be exists\"}","service.name":"filebeat","ecs.version":"1.6.0"}
```

I have attempted to reconcile this by creating an index named "nginx-log" (note, I've tried a custom name and nothing changed) and setting the following in `/etc/filebeat/filebeat.yml`:
```
setup.template.name: "nginx-log"
setup.template.pattern: "nginx-log"
```

The same error persisted. According to [Elasticsearch's documentation](https://www.elastic.co/guide/en/beats/filebeat/7.17/configuration-template.html), I should be able to manually map input fields. I've added the following to my `filebeat.yml`:
```
setup.template.append_fields:
- name: content
  type: text
```

Here are all my indicies:
```
~$ curl "http://localhost:4080/api/index" -u "admin:Complexpass123#"

{"article":{"name":"article","mappings":{"content":"text","publish_date":"time","status":"keyword","title":"text","user":"text"}},"nginx-log":{"name":"nginx-log","mappings":{"content":"text"}},"system-log":{"name":"system-log","mappings":{"content":"text"}}}
```

After adding the above `append_fields` setting, the following error occurs:
```
Mar 27 19:40:19 snail filebeat[20382]: {"log.level":"error","@timestamp":"2022-03-27T19:40:19.467Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":150},"message":"Failed to connect to backoff(elasticsearch(http://127.0.0.1:4080/es/)): Connection marked as failed because the onConnect callback failed: error loading template: failed to load template: couldn't load template: 400 Bad Request: {\"error\":\"error_type: parsing_exception, reason: [template] unknown option [data_stream]\"}. Response body: {\"error\":\"error_type: parsing_exception, reason: [template] unknown option [data_stream]\"}","service.name":"filebeat","ecs.version":"1.6.0"}
```

**Are you currently working around this issue?**
How are you currently solving this problem?
No known workaround.

**Additional context**
Anything else we should know?
I have not posted to the Filebeat forum as this seems like an error produced by Zinc. If this is user error related to Filebeat, please say so and I will inquire at the ES/Filebeat forum.

I would also like to note I needed to add the following extra settings in my `filebeat.yml` in order to avoid errors:
```
output.elasticsearch.allow_older_versions: true
```

```
Mar 27 15:03:36 snail filebeat[17143]: {"log.level":"error","@timestamp":"2022-03-27T15:03:36.289Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":150},"message":"Failed to connect to backoff(elasticsearch(http://localhost:4080/es/)): Connection marked as failed because the onConnect callback failed: Elasticsearch is too old. Please upgrade the instance. If you would like to connect to older instances set output.elasticsearch.allow_older_versions to true. ES=0.1.8, Beat=8.1.1.","service.name":"filebeat","ecs.version":"1.6.0"}
```

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by wrharding** [comment]
For now, I have started using variations of this one-liner to get logs into Zinc with as little resource utilization or complication as possible:

`tail -fn 0 /var/log/auth.log | while read line; do curl -XPUT "http://localhost:4080/api/system-log/document" -u "admin:pass" -d '{"content":"'"$line"'"}'; done;`

**Comment by hengfeiyang** [comment]
what version of Filebeat you used? i'll try it.

**Comment by wrharding** [comment]
```
# filebeat version
filebeat version 8.1.1 (amd64), libbeat 8.1.1 [7f30bb31a4a532c865161efbbdadd012323b04c5 built 2022-03-17 23:13:40 +0000 UTC]
```

**Comment by hengfeiyang** [comment]
i've fixed, you can have a try with latest code of main branch.

**Comment by wrharding** [comment]
I'm a bit out of my depth here, but I attempted to run with the lasted main branch code and got the following:

**Comment by wrharding** [comment]
I've manually installed NodeJS/NPM and Go via their respective methods:

```
root@snail:/opt/zinc# node -v
v17.9.0
root@snail:/opt/zinc# npm -v
8.5.5
root@snail:/opt/zinc# go version
go version go1.18 linux/amd64
root@snail:/opt/zinc#
```

I also made a slight change to the `build.sh` file as it was on the wrong arch for my system:

```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s -X main.Version=$VERSION -X main.Date=$DATE -X main.Commit=$COMMIT_HASH" -o zinc cmd/zinc/main.go
# CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-X main.Version=$VERSION -X main.Date=$DATE -X main.Commit=$COMMIT_HASH" -o zinc cmd/zinc/main.go
# CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="$ZINC_LDFLAGS" -o zinc cmd/zinc/main.go
```

**Comment by hengfeiyang** [comment]
You should npm install first

```
cd web/
npm install
``` 

then run build.sh again.

**Comment by wrharding** [comment]
Here is output of those commands after deleting the entire directory and cloning the repo again:

```
root@snail:/opt/zinc/web# npm install

added 401 packages, and audited 402 packages in 18s

68 packages are looking for funding
  run `npm fund` for details

1 critical severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
root@snail:/opt/zinc/web# cd ../
root@snail:/opt/zinc# vim build.sh
root@snail:/opt/zinc# bash build.sh
rm: cannot remove 'zinc': No such file or directory

> zinc-console@0.1.0 build
> vite build

vite v2.8.6 building for production...
transforming (221) node_modules/jsoneditor/dist/jsoneditor.min.js
<--- Last few GCs --->

[147668:0x4c88000]    15406 ms: Mark-sweep 251.7 (258.6) -> 250.8 (258.9) MB, 552.4 / 0.0 ms  (average mu = 0.250, current mu = 0.006) allocation failure scavenge might not succeed
[147668:0x4c88000]    16043 ms: Mark-sweep 251.9 (258.9) -> 251.1 (259.1) MB, 620.4 / 0.0 ms  (average mu = 0.142, current mu = 0.026) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb309a0 node::Abort() [node]
 2: 0xa4219e node::FatalError(char const*, char const*) [node]
 3: 0xd2389e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd23c17 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xedd045  [node]
 6: 0xeee48d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xef11be v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xeb2bda v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x1233038 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x16364b9  [node]
Aborted (core dumped)
embed.go:8:12: pattern web/dist: no matching files found
root@snail:/opt/zinc#
```

I appreciate the help!

**Comment by hengfeiyang** [comment]
Let me try with your node version

**Comment by hengfeiyang** [comment]
i use the version of nodejs in ubuntu 20.04:

```
root@nodejs:/data/go/src/github.com/prabhatsharma/zinc/web# node -v
v17.9.0
root@nodejs:/data/go/src/github.com/prabhatsharma/zinc/web# npm -v
8.5.5
```

run build is ok, if you virtual machine memory is too small?

i use virtual machine with 1G memory.

**Comment by wrharding** [comment]
I'll test it on a local machine with more memory tomorrow. I'm currently attempting to run it in a cloud VM with only 512MB of memory:

https://www.vultr.com/pricing/

Any ETA on when a new binary/release might occur?

**Comment by wrharding** [comment]
I was able to successfully build zinc on a separate machine with 2GB of memory. I'll setup a process for building the latest code. I still do not see logs coming in from Filebeat, but that may very well be a configuration issue on my end. I will continue testing. Note, there are no longer errors when trying to connect to zinc.

**Comment by hengfeiyang** [comment]
> I was able to successfully build zinc on a separate machine with 2GB of memory. I'll setup a process for building the latest code. I still do not see logs coming in from Filebeat, but that may very well be a configuration issue on my end. I will continue testing. Note, there are no longer errors when trying to connect to zinc.

you should delete `data/*`, because there was maybe error index template exists.

**Comment by hengfeiyang** [comment]
@bakman2 What is version you used, kibana and zinc?

**Comment by bakman2** [comment]
> @bakman2 What is version you used, kibana and zinc?

Not sure when you refer to kibana, do you mean filebeat ?

`filebeat version 8.1.3`

For zinc, i created a docker-compose with the image from the documentation. 
`public.ecr.aws/prabhat/zinc:latest`

**Comment by hengfeiyang** [comment]
Sorry, i asked for filebeat version, it's ok.

We changed docker image to `public.ecr.aws/h9e2j3o7/zinc:latest`

you can follow this page:

https://docs.zinclabs.io/04_installation/

**Comment by bakman2** [comment]
Ok now it seems to be working, thanks.

The interface has changed too, the search bar is growing with the width of the search results table.
Please consider removing `flex-wrap:wrap` from the first row so that the search interface remains visible. (safari 15.4)

![Screenshot 2022-04-25 at 20 18 31](https://user-images.githubusercontent.com/333960/165149895-ad94b5e2-c3fb-4da6-9204-b611123b3f50.jpg)
