### ISSUE TITLE
How to use golang to manipulate zinc？

### ISSUE THREAD

**Issue by noovertime7** [zinclabs/zinc#134]
As we all know, es can use golang client to add, delete and check data, so I was wondering if zinc can use code to do these operations, and if so how should I do it? Looking forward to your reply thanks!

**Comment by prabhatsharma** [comment]
We don't have SDKs for now. However HTTP APIs for zinc are well documented that you can use from Go.

**Comment by prologic** [comment]
is it possible to build interfaces for what is behind the HTTP API itself so that it becomes possible to use zinc as a library?

**Comment by prabhatsharma** [comment]
@prologic in that case you might as well go ahead and use bluge directly.
