### ISSUE TITLE
Add flag to disable/override Sentry

### ISSUE THREAD

**Issue by karatekaneen** [zinclabs/zinc#139]
Saw in [this commit](https://github.com/zinclabs/zinc/commit/9cecc4e78e64ba3a9af9ff5569275cba1085fc8a) that Sentry was added to track bugs. This would be an issue for us because of GDPR and other compliance issues. 

**Describe the solution you'd like**
I think that this should be behind a flag that we can disable and/or give possibility to change to our own Sentry instances.

**Comment by prabhatsharma** [comment]
Thanks for letting us know. I will add a flag that you can use to disable it.

**Comment by prologic** [comment]
Yes please either consider removing such features or making them "opt-in". This is mandatory in other cases as well for self-hosting, on-prem and sovereignty.

**Comment by karatekaneen** [comment]
Looks to be fixed in v0.2.0, nice!
