### ISSUE TITLE
0.1.9 & 0.2.0 login page is empty

### ISSUE THREAD

**Issue by eddyyuen** [zinclabs/zinc#144]
**Tell us about your request**
login ZINC

**Which service(s) is this relate to?**
http://localhost:4080/ui/

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
version : zinc_0.1.9_Windows_x86_64.tar.gz    zinc_0.2.0_Windows_x86_64.tar.gz 
Login page is empty . And has 2 JS errors.
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
/ui/assets/index.df1980fd.js
:4080/ui/assets/vendor.cf9ece94.js
```

**Comment by hengfeiyang** [comment]
I just tested ok on windows, Maybe it has browse cache, Can you clear your browse cache, and try again?

**Comment by eddyyuen** [comment]
It works! it is my fault !

**Comment by heliping** [comment]
same situation, how to solve?

**Comment by heliping** [comment]
![image](https://user-images.githubusercontent.com/24326525/167605459-67602cf7-be1c-4c1a-a41e-2e7911a934f7.png)

**Comment by hengfeiyang** [comment]
Can you clear your browse cache, and try again? @heliping
