### ISSUE TITLE
Why do I report this error in centos？

### ISSUE THREAD

**Issue by chenxi2015** [zinclabs/zinc#147]
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/13269485/167814205-468bf360-3bae-45a7-8054-13253ae15efa.png">

I am using root permission. What can I do?

error message
`
{"level":"fatal","time":"2022-05-11T09:08:41Z","message":"Error loading system index: error opening index: error setting up directory: error creating directory './data/_index_mapping': mkdir ./data/_index_mapping: permission denied"}
`

**Comment by hengfeiyang** [comment]
You should `chmod -R 777 /root/zinc_data`, in container, zinc run as a user that has no root privileges.

**Comment by chenxi2015** [comment]
> You should `chmod -R 777 /root/zinc_data`, in container, zinc run as a user that has no root privileges.

Yeah thinks.  It works. I just executed `chmod -R 777 ./data`
