### ISSUE TITLE
Question: "OR" query for strings and search_type parameter.

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [zinclabs/zinc#151]
Hi,

How can I query for docs like
Field_A OR Field_B OR Field_C contain TERM ?

Thank you.

**Comment by hengfeiyang** [comment]
you can do search like this:

POST /es/indexName/_search
```
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "filed_a": "value"
          }
        },
        {
          "term": {
            "filed_b": "value"
          }
        },
        {
          "term": {
            "filed_c": "value"
          }
        }
      ]
    }
  }
}
```

**Comment by nikolas-digitalBabylon** [comment]
Thank you! Generally speaking, search_type needs to be documented, unless I have missed it and in this case I would appreciate a hint/link.

**Comment by hengfeiyang** [comment]
We'll update our documents.

**Comment by nikolas-digitalBabylon** [comment]
It would be great if the docs contain some examples of each search_type and also a description of the differences of each search_type.

**Comment by prabhatsharma** [comment]
You could also use the query_string for OR searches.

e.g. Country:FRA City:Turin -> This will search for country=FRA OR City=Turin both City and country are OR 
e.g. Country:FRA +City:Turin -> Will result in mandatory result for Country: FRA (Optional) AND City:Turin (Mandatory)

You can try these queries at https://playground.dev.zincsearch.com/
