### ISSUE TITLE
Vector Search

### ISSUE THREAD

**Issue by payasguptagithub** [zinclabs/zinc#154]
**Is your feature request related to a problem? Please describe.**
My data contains arrays of floats and newer version of elastic search provides a way to find similar documents given an array. This is useful in common days as scientists store features in form of arrays and use cosine distance to find similar features

**Describe the solution you'd like**
I would like zinc to provide a similar functionality as elastic search so that I can replace elastic on our servers.

**Describe alternatives you've considered**
Currently there is no of the shelve solution out there except Elastic

**Additional context**

**Comment by prabhatsharma** [comment]
@payasguptagithub thanks. I will add this feature to the backlog. I will keep it open here so users can upvote it. Based on the community upvotes we can prioritize this.

**Comment by prabhatsharma** [comment]
Closing this for now as we do not have this in our near term roadmap for now.

**Comment by collimarco** [comment]
It would be extremely useful for AI applications to have vector search. There are literally entire databases built for that purpose and it would be useful to have this feature directly in Zincsearch. Postgresql and Elastic Search are already working on that.

Is it possible to reopen this?

**Comment by helixworld** [comment]
I think Pincecone and Weaveaite are some of the alternatives

**Comment by prabhatsharma** [comment]
There are 3 very good open source alternatives for this that I can recommend milvus, weavite and qdrant.
