### ISSUE TITLE
Feature Request: Generate API docs using Swagger

### ISSUE THREAD

**Issue by theodesp** [zinclabs/zinc#156]
**Is your feature request related to a problem? Please describe.**

First of all, great job on this one!

I would be great as a developer using this service to have a live view of the API and issue requests without using the UI. It would also be useful to have a Swagger file so that developers can generate compatible clients with this engine.

**Describe the solution you'd like**

I would like to have the way to view a live API documentation for the search engine ideally using Swagger OpenAPI specs.

**Describe alternatives you've considered**

Inspecting the endpoints using the code however this is not very good documented.
I also reviewed the existing docs which only offer a static representation of the API with limited examples.

**Additional context**

gin-swagger can help here:
https://github.com/swaggo/gin-swagger

I would be interested in contributing to this feature if it's OK

**Comment by prabhatsharma** [comment]
It's a great feature to have. Would love to have a PR on this.

**Comment by prabhatsharma** [comment]
closing in favor of #180
