### ISSUE TITLE
Provide drop down to select UI language (i18n)

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zinc#160]
**Is your feature request related to a problem? Please describe.**
i18n support is added, but does not have a mechanism in the UI to select the particular language

**Describe the solution you'd like**
A drop down at the right hand side top to select the required language.

**Describe alternatives you've considered**
manually edit cookie

**Comment by hengfeiyang** [comment]
[@https://github.com/zinclabs/zinc/pull/161](https://github.com/zinclabs/zinc/pull/161)
