### ISSUE TITLE
Implement Write Ahead Log(WAL)

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zinc#165]
**Is your feature request related to a problem? Please describe.**
Currently there is no WAL which means that in scenarios of node crashes there is a possibility of data loss. Having WAL will also improve data ingestion performance.

**Describe the solution you'd like**
When messages hit the ingestion API endpoints, instead of trying to index them right away the message should be stored in a WAL and confirmation should be sent back to the sender that the message has been accepted. We should asynchronously read messages from the WAL and index them. After indexing is done the message should be removed from WAL.

**Describe alternatives you've considered**
Externalize WAL using kafka/redpanda. This would make the architecture much more complex.

**Additional context**
https://github.com/tidwall/wal could be researched for suitability of WAL implementation

https://pkg.go.dev/go.etcd.io/etcd/wal can also be researched

**Comment by dranikpg** [comment]
In what case is a data loss currently possible if the confimation is sent after a bluge writer has updated the index?

---

Elasticsearch aggregates changes to avoid persisting the index after each update. Those are applied once every second (by default) in batches. To not lose the data before peristance, the raw data is saved in a [so called Translog](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html). This is why elastic is near realtime and search is not instantly available. It only allows CRUD operations on the document until it is persisted.

The way ES works is pretty similar to what you described.

This looks like an interesting task. I'd be eager to take this up if possible 😃

**Comment by prabhatsharma** [comment]
You understood it correctly. I researched https://pkg.go.dev/go.etcd.io/etcd/wal  and it was not appropriate. I am experimenting with https://github.com/tidwall/wal . What are your thoughts on it?

**Comment by dranikpg** [comment]
Should fit. The first one is too specialized and is for finer grained storages.

Because the log exists per index and is read entirely on indexing, we don't need anything besides appending to the log and clearing it. Clearing can be done by keeping two parallel logs: one for writes, one for reads during indexing. That would be a lot simpler than tidwall

**Comment by hengfeiyang** [comment]
implementing... https://github.com/zinclabs/zinc/tree/wal
