### ISSUE TITLE
Back single ZincSearch index by multiple bluge indexes

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zinc#169]
**Is your feature request related to a problem? Please describe.**
Currently  1 zinc index corresponds to 1 backing bluge index. This limits the amount of data that can be stored in a single index. Write performance starts deteriorating after bluge index size crosses 50GB.

**Describe the solution you'd like**
A single zinc index can be backed by multiple bluge indexes. No bluge index should be greater than 10GB each. This would require parallel searches in multiple indexes and aggregating the results before returning it to user.

**Describe alternatives you've considered**
Creating smaller indexes and many of them. High volume of incoming data where we consume 100+GB of data everyday in a single index would still be a problem.

**Comment by hengfeiyang** [comment]
working on branch [multiple-index](https://github.com/zinclabs/zinc/tree/multiple-index)

**Comment by hengfeiyang** [comment]
Created PR https://github.com/zinclabs/zinc/pull/202
