### ISSUE TITLE
Would be nice to have some benchmarks against ES, Sonic, and Toshi. I am very much interested in stress-testing on large dataset.

### ISSUE THREAD

**Issue by zhy1** [zinclabs/zinc#171]
Would be nice to have some benchmarks against ES, Sonic, and Toshi. I am very much interested in stress-testing on large dataset.

**Comment by gedw99** [comment]
hey @zhy1 

i am also quite curious about Perf.

Do you have links to those last 2 ones ?

**Comment by prabhatsharma** [comment]
ZincSearch is currently PreGA. It does not have things like sharding, WAL, caching and as such any performance becnhmarks are not really fair comparison to others. Once we have theese things available in ZincSearch we will run benchmarks.

**Comment by prabhatsharma** [comment]
Closing in favor of https://github.com/zinclabs/zinc/issues/312
