### ISSUE TITLE
index undefined does not exists

### ISSUE THREAD

**Issue by maxzhang666** [zinclabs/zinc#173]
in the search page
when i click refersh,the left side is show some field
but now the index selector is empty
and in this time i chose some filed,i got this error ```index undefined does not exists```

**Comment by hengfeiyang** [comment]
1, Please select index first, then you will see it work well.
2, The index size update was trigger by insert documents,  it will update when you insert a document.

**Comment by maxzhang666** [comment]
> 1, Please select index first, then you will see it work well. 2, The index size update was trigger by insert documents, it will update when you insert a document.

tks,i just report this
