### ISSUE TITLE
runtime error: slice bounds out of range [:13130] with capacity 0

### ISSUE THREAD

**Issue by 284330505** [zinclabs/zinc#175]
Single log file > 500m
The error is as follows：
runtime error: slice bounds out of range [:13130] with capacity 0
/usr/local/go/src/runtime/panic.go:108 (0x432eb4)
/go/pkg/mod/github.com/zinclabs/ice@v0.2.1-0.20220504041539-ace50a7ef71f/read.go:52 (0x9aac25)
/go/pkg/mod/github.com/zinclabs/ice@v0.2.1-0.20220504041539-ace50a7ef71f/read.go:22 (0x9aa8c4)
/go/pkg/mod/github.com/zinclabs/ice@v0.2.1-0.20220504041539-ace50a7ef71f/segment.go:197 (0x9ab8d3)
/go/pkg/mod/github.com/zinclabs/ice@v0.2.1-0.20220504041539-ace50a7ef71f/segment.go:190 (0x9ab796)
/go/pkg/mod/github.com/blugelabs/bluge@v0.1.9/index/segment.go:61 (0x9be0c5)
/go/pkg/mod/github.com/blugelabs/bluge@v0.1.9/index/snapshot.go:307 (0x9bdfa6)
/go/pkg/mod/github.com/blugelabs/bluge@v0.1.9/search/search.go:134 (0xee3fea)
/go/src/github.com/zinclabs/zinc/pkg/core/search_v2.go:96 (0xee3a41)
/go/src/github.com/zinclabs/zinc/pkg/core/search_v2.go:66 (0xee3812)
/go/src/github.com/zinclabs/zinc/pkg/handlers/v2/search.go:57 (0xf4df24)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xf3df69)
/go/src/github.com/zinclabs/zinc/pkg/auth/authmiddleware.go:29 (0xf3ddb2)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xf50586)
/go/src/github.com/zinclabs/zinc/pkg/routes/httpcache.go:40 (0xf50572)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xf5001b)
/go/src/github.com/zinclabs/zinc/pkg/routes/accesslog.go:32 (0xf4fffe)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x912aa1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x912a8c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x911970)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x9115d8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x911111)
/usr/local/go/src/net/http/server.go:2879 (0x6ac2fa)
/usr/local/go/src/net/http/server.go:1930 (0x6a79a7)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x4670c0)

**Comment by prabhatsharma** [comment]
Can you try the latest release - https://github.com/zinclabs/zinc/releases/tag/v0.2.2

**Comment by prabhatsharma** [comment]
Can you try the latest release

**Comment by prabhatsharma** [comment]
@284330505 Let us know if you have been able to resolve the issue after upgrading to 0.2.3
