### ISSUE TITLE
search in all indices

### ISSUE THREAD

**Issue by B0bbyD0llar** [zinclabs/zinc#18]
Is it possible to search in all indices?

and

is it possible to search without start and end date?

**Comment by prabhatsharma** [comment]
Is it possible to search in all indices?
> Currently no.

is it possible to search without start and end date?
> Currently no. But should be trivial to make this change. I will work on this shortly when I get some time.

**Comment by Sterginsy** [comment]
S

**Comment by hengfeiyang** [comment]
you can try v0.1.7, it's already supported you mentioned.
