### ISSUE TITLE
Swagger API Docs - Implement the rest of the Endpoints

### ISSUE THREAD

**Issue by theodesp** [zinclabs/zinc#180]
**Is your feature request related to a problem? Please describe.**
This is a continuation ticket for https://github.com/zinclabs/zinc/pull/178.  Now that we have Swagger support in zinc, we would like to provide the rest of the API Docs.

**Describe the solution you'd like**
Provide the rest of the Swagger API Documentation by annotating the API Endpoints using https://github.com/swaggo/gin-swagger Comments.

**Additional context**
Use following checklist to keep track of the Current and Missing Docs:

**Auth**

- [x] List
- [x] Delete
- [x] CreateUpdate
- [x] Login

**index**

- [x] Index
- [x] List
- [x] Create
- [x] Delete

**index settings**
- [x] Get Mapping
- [x] Update Mapping
- [x] Get Settings
- [x] Update Settings

**Search**

- [x] Search
- [x] Bulk Insert
- [x] Update Document
- [x] Delete Document
- [x] Crete Document

**ES**

- [ ] License
- [ ] _xpack
- [x] _search
- [x] _msearch
- [x] :target/_search
- [x] :target/_msearch
- [x] _index_template
- [x] _index_template/:target
- [x] :target/_mapping
- [x] :target/_settings
- [x] _analyze
- [x] :target/_analyze
- [x] _bulk
- [x] :target/_bulk
- [x] :target/_doc
- [x] :target/_doc/:id

**Comment by theodesp** [comment]
@prabhatsharma it would be useful to add some `help-wanted`, `good-first-issue` labels here. Thank you.

**Comment by prabhatsharma** [comment]
@theodesp Thanks. Added

**Comment by sgulci** [comment]
Hi, @prabhatsharma I wanna do this, it is a good way to start learning more about Zinc. 

did not mention in [this](https://github.com/zinclabs/zinc/blob/main/CONTRIBUTING.md)  but I think, fork and PR from there, is the way to contribute to this project, right?

**Comment by prabhatsharma** [comment]
Thanks. Appreciate it. Yes - fork and PR is the way to go. I will update the guide.

**Comment by sgulci** [comment]
Hi @prabhatsharma 

Created a PR about this issue, but I did it with minimal changes possible, write in PR  but there are some notes about API we should clarify for future task I think, these are :
 
1 - The user list returns Searchresponse which is I think is wrong, but I understand that there is gonna be a UI job to change, this can be addressed by creating a new task

2 - For swagger in this first phase I did not change any object without discussing it with maintainers first, for example, it could be a good idea to return errors object every rest endpoint for a more stable API

3 - It could be a good idea to divide posts and put functions in user service, and there are not enough checks for user objects like checking Name, Password, and Role properties

4 - Same handler methods for multiple Rest endpoints are getting problems for putting them in the swagger page, we have to choose one path, little indirection could solve this problem 

5 - In the bulk services there are no particular object requests, it is all done with scanner utils with reading line by line, for clarity there can be request object for this

Best
Sahin

**Comment by sgulci** [comment]
hey, @prabhatsharma @hengfeiyang  did you find the time to assess the above points, I think there will be an improvement for users too,  I can create tickets and PR for the above points and discuss them, I understand this is a low priority right now

**Comment by hengfeiyang** [comment]
Some issue i'm working on, let's talk about it later.

**Comment by hengfeiyang** [comment]
@sgulci As you mentioned:

`1 - The user list returns Searchresponse which is I think is wrong, but I understand that there is gonna be a UI job to change, this can be addressed by creating a new task`

I changed the response to a user list.

`2 - For swagger in this first phase I did not change any object without discussing it with maintainers first, for example, it could be a good idea to return errors object every rest endpoint for a more stable API`

I added a struct `meta.HTTPResponse` for normal returns like `message` or `error`.


For 3,4,5 issues:

I haven't good ideas, for compatible so we have one API on POST or PUT. And some API have very complex query body, if you have any ideas please let we know.

**Comment by prabhatsharma** [comment]
Done with 

https://github.com/zinclabs/zinc/pull/205
https://github.com/zinclabs/zinc/pull/208
https://github.com/zinclabs/zinc/pull/220
