### ISSUE TITLE
mapping can not update

### ISSUE THREAD

**Issue by maxzhang666** [zinclabs/zinc#181]
Updating the mapping will prompt that it already exists

And

The ```api/index``` can be created normally

The ```/es/:target/_mapping``` can only create an empty mapping

**Comment by hengfeiyang** [comment]
The document description is error, with the version, you need update mapping with the data:

```json
{
    "mappings": {
        "properties": {}
    }
}

```

next version, we will fix it.

**Comment by maxzhang666** [comment]
> The document description is error, with the version, you need update mapping with data:
> 
> ```json
> {
>     "mappings": {
>         "properties": {}
>     }
> }
> ```
> 
> next version, we will fix it.

tks

**Comment by liuwenchao** [comment]
Fixed? @hengfeiyang

**Comment by hengfeiyang** [comment]
You can update mapping use the latest version, if you have new problem, please create a new issue, thanks.
