### ISSUE TITLE
Better error messaging - when no write access to data folder

### ISSUE THREAD

**Issue by alecthomas** [zinclabs/zinc#187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Attempting to [run ZincSearch](https://docs.zincsearch.com/installation/) through Docker on my M1 laptop results in:
```
$ docker run --rm -e ZINC_DATA_PATH="/data" -v $PWD/data:/data -p 4080:4080 -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=admin --name zinc public.ecr.aws/zinclabs/zinc:latest
{"level":"fatal","error":"while opening memtables error: while opening fid: 1 error: while updating skiplist error: mremap size mismatch: requested: 20 got: 134217728","time":"2022-06-04T21:35:59Z","message":"open badger db for metadata failed"}
```

Which appears to be a bug in [Badger](https://discuss.dgraph.io/t/error-mremap-size-mismatch-on-arm64/15333/8).

**Comment by prabhatsharma** [comment]
It's not really a bug in badger. It seems zinc could not get permission to write to data folder. ZincSearch runs in unprivileged mode in a container and that can cause this issue.

Check this issue - https://github.com/zinclabs/zinc/issues/23

**Comment by prabhatsharma** [comment]
Try chmod a+rwx $PWD/data

**Comment by alecthomas** [comment]
Ah yes, right you are. Correctly creating `$PWD/data` fixed it.

Perhaps the error message could be improved somewhat for this case?

**Comment by prabhatsharma** [comment]
Yeah, we need better messaging. Adding to our backlog.

**Comment by hengfeiyang** [comment]
https://github.com/zinclabs/zinc/commit/4c4812633907c3fd31bea4da72efcec75801b615
