### ISSUE TITLE
Support tools from other projects

### ISSUE THREAD

**Issue by ADeeeee** [zinclabs/zinc#189]
Zinc finally supports Grafana recently. Yes! Although there is a beautiful UI in Zinc, but I'm wondering that I could use other UI tools querying and managing the data because I had already multiple ElasticSearch clusters and it'd be nice to manage them together.

ElasticHead, ElasticVue...etc. are all nice tools. I would like to use it via http://HOST_IP:4080/es, but unfortunately unreachable even though both are in the same subnet without any firewall rules. BTW, Grafana could reach it at the same time.

Is it possible for people choosing the UI tool they prefer in the future?

**Comment by prabhatsharma** [comment]
This requires supporting a lot of elasticsearch APIs. The ones that I could quickly check are:

1. /_nodes/stats
2. /_cluster/state
3. /_nodes
4. /_stats
5. /_cluster/health
6. /_all

Its's not a priority for us right now, but happy to get a PR on this.
