### ISSUE TITLE
Search Types

### ISSUE THREAD

**Issue by B0bbyD0llar** [zinclabs/zinc#20]
Is there a more detailed explanation of the search types somewhere?
Are the named search types already implemented in a functional way?

**Comment by prabhatsharma** [comment]
We will have to build a documentation for the project. In the meanwhile some explanation is available at https://blevesearch.com/docs/Query/ . Most of the ones in README are functionally implemented, but not all.

**Comment by B0bbyD0llar** [comment]
@prabhatsharma thanks. That helps.

I don't get it. How can i search for a part of a string. Like 'DEMT*' should find all documents which contains terms that starts with "DEMT"

**Comment by prabhatsharma** [comment]
search query from zinc console uses querystring search type which does not do prefix searches :-( . We need to work on the query language to include it.

**Comment by prabhatsharma** [comment]
@B0bbyD0llar You could actually use wildcard search though. 

e.g 

Search text starting with par . e.g. Paris, Parthenon, Part, Paramater
par*

**Comment by isara-ovin** [comment]
Hi @prabhatsharma is it possible to do a exact match on one filed and then a match on other fields?

suppose I have an address like `123 Main st FL 34567`

and in zinc I have it as `{number: 123, street: 123 Main st, state: FL, zip: 34567}`
can I do an exact match at _number_ field and then a match at other fields?

**Comment by isara-ovin** [comment]
Thank you @prabhatsharma ill give this a try. I have proposed the platform to our company, ill be doing a R&D soon ill let you know how it goes
