### ISSUE TITLE
Push logs to the zinc search engine in a simple way

### ISSUE THREAD

**Issue by coastsee** [zinclabs/zinc#217]
Hello, I have developed a simple tool that can push logs to the zinc search engine in batches. It is very simple and convenient to use, Maybe it can help users get started with zinc faster. Can you recommend it in the zinc project document? 😄hh~

[https://github.com/coastsee/logpush](https://github.com/coastsee/logpush)

**Comment by hengfeiyang** [comment]
Thanks for you works, It looks just a personal project and at an earlier stage. 

Do you interesting at build a Client SDK for Zinc, that will be more helpful for users.

**Comment by coastsee** [comment]
Thanks for your reply. I'll try it if I have time.
