### ISSUE TITLE
What are tese messages about, Error while sending post request. 

### ISSUE THREAD

**Issue by kcubeterm** [zinclabs/zinc#219]
![Screenshot_20220621-134945_Termux](https://user-images.githubusercontent.com/50498359/174752426-3c1f1de0-abf4-435f-9581-504ea9f2ccfd.png)

Is this any kind of telemetry ? If it, How to disable it

**Comment by prabhatsharma** [comment]
You can find more info about telemetry and how to disable it at https://docs.zincsearch.com/telemetry/

**Comment by kcubeterm** [comment]
Thanks
