### ISSUE TITLE
UI: Unable to perform search after indexing 1.9m names

### ISSUE THREAD

**Issue by prashantkhandelwal** [zinclabs/zinc#222]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Which service(s) is this relate to?**
GUI - Search

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
I imported 1.9 million artist names from MusicBrainz data dump using bulk insert. All records were indexed successfully. Now when I navigate to the search page, it won't render the data as it used to do before. I started with the Olympics dataset and it worked fine and now after create this new index and inserting data, Olympics index also stopped working in the UI.

The API is working fine and responding to the search queries without any issues. 

**Are you currently working around this issue?**
No

**Additional context**
I see that when we select the index from the dropdown, an API request is made to the backend for _search which returns all the records in response. If this response can be limited for large datasets like around 10K or more or less (whatever number works best) then I believe the UI will be able to respond quickly.

**Attachments**
Here is the screenshot of the UI stuck on loading - 

![image](https://user-images.githubusercontent.com/1306711/175021890-94b177ce-2e79-4710-889a-d7120ef65683.png)

This is the sever log screenshot. You can see the requests made to the _search endpoint. Apart from this there is no other informaiton in the server logs which could help.

![image](https://user-images.githubusercontent.com/1306711/175023103-e25325fa-cccc-4dd1-8925-712c9f74e370.png)

**Comment by rstoof** [comment]
Could it be that the half hour ago you select has been passed? On the right of the search bar select full-time?

**Comment by prashantkhandelwal** [comment]
Yep! It worked. Selecting full-time did the trick. Thanks
