### ISSUE TITLE
hits.hits returns null instead of [] for empty search results

### ISSUE THREAD

**Issue by wsw70** [zinclabs/zinc#226]
**Note** 

I am not sure if this is a bug, it may be a will to adhere to ES format.

**Tell us about your request**

In case where there are no hits in a search, a `null` is sent back:

```json
{
  "took": 0,
  "timed_out": false,
  "hits": {
    "total": {
      "value": 0
    },
    "max_score": 0,
    "hits": null
  },
  "error": ""
}
```

**Which service(s) is this relate to?**

The Search API

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**

The expected return is an Array, in this case we should have `hits: []` instead of `hits: null`

**Are you currently working around this issue?**

I add an extra `if (result.hits.hits)` before analyzing the results, instead of a bare `result.hits.hits.forEach....`). The code would be simplified if the proper structure was returned.

**Comment by hengfeiyang** [comment]
https://github.com/zinclabs/zinc/commit/ebc380e24c016f6f8294c5a93bc3b3235041a428

Fixed.
