### ISSUE TITLE
A GUI operation made the GUI irresponsive, crashed the docker host server and now indexes are not read

### ISSUE THREAD

**Issue by wsw70** [zinclabs/zinc#233]
**Tell us about your request**

A specific sequence in the GUI made zinc crash, the server issue an OOM kill request and the database is corrupted (I think).
Docker installation (public.ecr.aws/h9e2j3o7/zinc:latest), version 0.2.5, commit hash e0fbeac24f8b685c51e0625b55a002961853d31b

The crash was on Jun 26 14:14:23 CET, the latest image above was pushed "about 21 hours ago", which sets it at about 20:00 CET Jun 26.
It is therefore likely that the bug happened with the previous image (0.2.4). Was there a data format change maybe?

**Which service(s) is this relate to?**

GUI, then the zinc engine

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**

I have a few small indexes (5 x ~1 MB) as I am testing zinc as a hub for my home lab. At some point, I made a search by choosing a timeframe, the search was ongoing, then I switched to a longer relative time, and finally to the "all times" switch.
I then realized that I forgot to select an index, selected one and the page became irresponsive.

And so was the whole server (zinc runs in a docker container).

I forcefully rebooted it, and when looking at the logs I saw that there was an OOM message from the kernel that killed zinc (but it was too late, I was already on my way to reboot the server).

This is not fantastic but I can be careful with the front end.

The main problem is that after a restart of the server (and zinc's container) I do not see anymore neither the users I configured nor the indexes.

When going to the mapped volume, I do see the directories corresponding to my indexes, there are `.seg` and `.snp` files inside.
I also have backups of these files if needed (which BTW bring the question of how correctly backup zinc)

→ how can I have zinc reuse the indexes?

**Are you currently working around this issue?**

I am not.

**Comment by hengfeiyang** [comment]
For now, zinc can't start report any log? Or just there is no data shows in UI?

If zinc can start and no error, just no data in UI, you can set ENV `ZINC_METADATA_STORAGE=badger` to fix it.

Because we change the default metadata storage in v0.2.5.

**Comment by wsw70** [comment]
> If zinc can start and no error, just no data in UI, you can set ENV `ZINC_METADATA_STORAGE=badger` to fix it.

I tried this, I see the indexes, but when trying to search (in the UI), I get an error:
![image](https://user-images.githubusercontent.com/1345886/176109951-690c7c32-a9ff-42cc-86df-ee1bac98dbf9.png)

**Comment by hengfeiyang** [comment]
And maybe you need set ENV `ZINC_ICE_COMPRESSOR=s2`

**Comment by wsw70** [comment]
> And maybe you need set ENV ZINC_ICE_COMPRESSOR=s2

Thank you - these two lines together helped, I see data both via the UI and the api.
