### ISSUE TITLE
Highlight api in search doesn't work

### ISSUE THREAD

**Issue by ag321123** [zinclabs/zinc#271]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
What do you want to see in Zinc?

**Which service(s) is this relate to?**

Highlight API for search

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.

Trying to use the highlight api to understand  it and see what it does. 

This query works:

{
          "search_type": "match",
          "from": 0,
          "max_results": 20,
          "_source": [],"query": { "term": "Dracula" }}

But when I add the highlighting data, as shown on page https://docs.zincsearch.com/api/search/highlight/,  I get an error.

{
          "search_type": "match",
          "from": 0,
          "max_results": 20,
          "_source": [],
          "highlight": {
            "fields": {
                "contents": {
                  "pre_tags": [],
                  "post_tags": []
                }
            }
        },"query": { "term": "Dracula" }}

The error is:

{"error":"json: cannot unmarshal object into Go struct field QueryHighlight.highlight.fields of type []string"}

The following code: 

type QueryHighlight struct {
	Fields []string `json:"fields"`
	Style  string   `json:"style"`
}

from types.go seems to be the problem. It doesn't match the documentation on the highlight api. It is expecting an array of fieldnames, not the structure shown in the documentation.

**Are you currently working around this issue?**
How are you currently solving this problem?

I don't have a solution.

**Additional context**
Anything else we should know?

No.

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

Thanks,

Allan

**Comment by hengfeiyang** [comment]
Thanks for report, it not implement in search v1, we will fix it in next release.

**Comment by prabhatsharma** [comment]
You can use the docker image - public.ecr.aws/zinclabs/zinc:0.2.6-8bd5647-dev

or binaries from - http://zincsearch-releases.s3-website-us-west-2.amazonaws.com/#zincsearch/0.2.6-8bd5647-dev-2022-07-11T16:03:23Z/
