### ISSUE TITLE
Parallel query across shards for an index

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zinc#313]
**Is your feature request related to a problem? Please describe.**
Currently indexes are sharded. However when querying a particular zinc index, we use bluge multisearch API which queries indexes serially. In order to improve performance of query we need to be able to query bluge indexes in parallel.

**Describe the solution you'd like**
Parallel querying of bluge indexes. This can be done in bluge library directly or it can be achieved in zinc. We will need to join search results and aggregations from multiple bluge indexes in order to achieve this well.

**Describe alternatives you've considered**
N/A

**Additional context**
None

**Comment by beocaca** [comment]
asd
