### ISSUE TITLE
GUI: Add refresh button on Index page

### ISSUE THREAD

**Issue by prabhatsharma** [zinclabs/zinc#315]
**Is your feature request related to a problem? Please describe.**
Currently a hard refresh of the Index page is required in order to load the new index list and stats.

**Describe the solution you'd like**
A refresh button will help get the latest index list and stats.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hengfeiyang** [comment]
You can thought click the search icon to refresh indexes list from server.
