### ISSUE TITLE
Unescaped format for nginx json log

### ISSUE THREAD

**Issue by devig** [zinclabs/zinc#316]
I forward stdout of docker-compose to fluent-bit and zinc. How to remove unnecessary escaping for key "log"? I expected "log" as json-field
Actual result:
{
  "_index": "stdout",
  "_type": "_doc",
  "_id": "6dc987ae-0530-82c6-06f3-f6115153b088",
  "_score": 2,
  "@timestamp": "2022-07-12T13:32:20Z",
  "_source": {
    "container_id": "a78ceeec09408ca28afcbb025ca4c51c3437c3cab8b9ca2cbff72f7848febbd8",
    "container_name": "/nginx",
    "log": "{ \\"timestamp2\\": \\"1657632740.811\\", \\"remote_addr\\": \\"185.71.52.6\\", \\"body_bytes_sent\\": 32, \\"request_time\\": 0.002, \\"response_status\\": 200, \\"request\\": \\"GET /?qwe=asd HTTP/1.1\\", \\"request_method\\": \\"GET\\", \\"http_user_agent\\": \\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36\\",\\"http_x_identifier\\": \\"-\\",\\"upstream_addr\\": \\"127.0.0.1:9000\\",\\"http_cf_ipcountry\\": \\"-\\",\\"http_cf_connecting_ip\\": \\"-\\", \\"http_x_token\\": \\"-\\" }",
    "source": "stdout"
  }
}

Expected result:
{
  "_index": "stdout",
  "_type": "_doc",
  "_id": "6dc987ae-0530-82c6-06f3-f6115153b088",
  "_score": 2,
  "@timestamp": "2022-07-12T13:32:20Z",
  "_source": {
    "container_id": "a78ceeec09408ca28afcbb025ca4c51c3437c3cab8b9ca2cbff72f7848febbd8",
    "container_name": "/nginx",
    "log": "{ "timestamp2": "1657632740.811", "remote_addr": "185.70.52.12", "body_bytes_sent": 32, "request_time": 0.002, "response_status": 200, "request": "GET /?qwe=asd HTTP/1.1", "request_method": "GET", "http_user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36","http_x_identifier": "-","upstream_addr": "127.0.0.1:9000","http_cf_ipcountry": "-","http_cf_connecting_ip": "-", "http_x_token": "-" }",
    "source": "stdout"
  }
}
Current docker-compose.yml 
https://gist.github.com/devig/81fd80df35afc89e7930dd323e874245

**Comment by prabhatsharma** [comment]
While I have not tried this personally, it looks like this is exactly what you need - https://docs.fluentbit.io/manual/v/1.3/parser/decoder

**Comment by devig** [comment]
> Can you provide your fluent-bit config?

https://gist.github.com/devig/81fd80df35afc89e7930dd323e874245 - here is all configs

fluent-bit.conf
[SERVICE]
    Log_Level    info
    Flush        1
    Parsers_File parsers.conf

[INPUT]
    Name  forward


[OUTPUT]
    Name   es
    Index  stdout
    Host   zinc
    Port   4080
    Path   /es
    Type   journal
    Match  *
    Generate_ID On
    HTTP_User admin
    HTTP_Passwd complexpass12
    Trace_Error On
    Buffer_Size 25M

parsers.conf
[PARSER]
    Name         forward
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
#    Decode_Field_As   escaped_utf8    log    do_next
#    Decode_Field_As   json       log

**Comment by devig** [comment]
> While I have not tried this personally, it looks like this is exactly what you need - https://docs.fluentbit.io/manual/v/1.3/parser/decoder

I have tried `Decode_Field_As   json       log`  nothing changed.

**Comment by hengfeiyang** [comment]
Because, you config a parser but will not be used.

You should add a section `filter` like this:

```
[INPUT]
    Name         forward

[FILTER]
    Name parser
    Match *
    Key_Name log
    Parser   json
    Preserve_Key Off
    Reserve_Data On
```

**Comment by devig** [comment]
@hengfeiyang it's work! Thanks a lot. Is it possible to log docker-compose stdout to zinc use vector?

**Comment by hengfeiyang** [comment]
@devig Thanks, We will consider it.
