### ISSUE TITLE
Duplicated documents in the index

### ISSUE THREAD

**Issue by yogi12314** [zinclabs/zinc#331]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Duplicated documents in the index

**Which service(s) is this relate to?**
API Reference ES Compatible

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
I have a problem with duplicate documents. I use bulk update sending 10,000 documents per request. Documents are the same except _timestamp and _score. The IDs provided are the equivalents of the IDs in our database. During testing with around 10,000 documents, update worked fine, but now I have over 4 million duplicated documents.

**Are you currently working around this issue?**
No

**Additional context**
An example of the default fields for duplicate documents.
{
  "_index": "Zamowienie",
  "_type": "_doc",
  "_id": "4519078",
  "_score": 11.09933503971557,
  "@timestamp": "2022-07-15T15:08:17.064496928Z",
  "_source": {...}
}

{
  "_index": "Zamowienie",
  "_type": "_doc",
  "_id": "4519078",
  "_score": 11.102457531322475,
  "@timestamp": "2022-07-12T13:10:43.023174254Z",
  "_source": {...}
}

**Attachments**
None

**Comment by prabhatsharma** [comment]
I am not sure I actually understand the problem. Are you expecting zinc to deduplicate records for you during ingestion or are you saying there are different documents with same id?

**Comment by yogi12314** [comment]
There are the same documents with the same id. Added by bulk update endpoint with specified id.

**Comment by hengfeiyang** [comment]
Yeah, for current version, if you use bulk API to index documents with same docID, it maybe duplicated. if you want update a document you should use update API. 

https://docs.zincsearch.com/api/document/update/

We are considering if we can guarantee  it not duplicated with bulk API. if have any progress, will let you know.
