### ISSUE TITLE
An error of “panic: runtime error: invalid memory address or nil pointer dereference”

### ISSUE THREAD

**Issue by xiaojun207** [zinclabs/zinc#332]
panic: runtime error: invalid memory address or nil pointer dereference

<img width="809" alt="image" src="https://user-images.githubusercontent.com/10277455/179348564-ca215f61-94a9-4db1-81e3-1a28839df9e3.png">

**Comment by prabhatsharma** [comment]
What version are you using?

**Comment by xiaojun207** [comment]
> What version are you using?

The Current main branch
