### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by xiaojun207** [zinclabs/zinc#333]
Start zinc, and nothing to do. The cpu from 35% to 200%, only use one mintue.

Test env:
Indexes: 3289

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/10277455/179350631-3e43d963-0111-460d-9ae5-3103cfd65b69.png">

**Comment by prabhatsharma** [comment]
What version are you using?

**Comment by xiaojun207** [comment]
> What version are you using?

The Current main branch

**Comment by hengfeiyang** [comment]
I did the same test and got the same result, but when i restart zinc, the cpu down to normal level. i think this is because we concurrency opened too many indexes. i think we can do that:

```
Close inactive index after 10m
```

**Comment by hengfeiyang** [comment]
@xiaojun207 I found this reason is we created one gorutine for each index, so when you have 3000+ indexes, it will have 3000+ gorintue to do WAL every second.

We changed implement to a global queue limit the gorutine num to 10(default), the cpu will down to normal level.

Can you try it again?
