### ISSUE TITLE
GET /es endpoints won't work

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zinc#338]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
I tried to GET /es endpoints using docker image. But there is no such endpoint :)

**What action did you take?**

**What action/response/output did you expect?**

**What actually happened?**

**How to reproduce the issue?**

**What version of ZincSearch are you using?**
public.ecr.aws/m5j1b6u0/zinc:v0.1.1

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

**Any attachments/screenshots?**

**Which service(s) is this relate to?**
API

**Comment by prabhatsharma** [comment]
Can you use public.ecr.aws/zinclabs/zinc:latest image

**Comment by amirEBD** [comment]
I used it :)
But the point is that I can't login to the zinc :))))

**Comment by hengfeiyang** [comment]
If you want to use UI, please use http://localhost:4080/

If you want to ingress with ES compatible API, please use http://localhost:4080/es/

**Comment by amirEBD** [comment]
Thank for your quick responding,
The problem was with the new environment set by zinc.
** Previuose env **: _FIRST_ADMIN_PASSWORD FIRST_ADMIN_USER_
** New env **: _ZINC_FIRST_ADMIN_PASSWORD ZINC_FIRST_ADMIN_USER_

**Comment by hengfeiyang** [comment]
Yes, we change it for a long time, all ENV set a prefix `ZINC_`

https://docs.zincsearch.com/environment-variables/
