### ISSUE TITLE
Handling of 'AUTO' in match query with Fuzziness

### ISSUE THREAD

**Issue by ayush71994** [zinclabs/zinc#375]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I am using match query with Fuzziness set as 'Auto'. If i run a  query with spaces in it, the match query tokenizes the same and searches for individual tokens in the index. However, it decides the fuzziness on the basis of length of query rather than length of token, which leads to weird results. 
Eg: 
Sample Query
```
{
    "query":
    {
        "bool":
        {
            "must":
            [
                {
                    "bool":
                    {
                        "minimum_should_match": 1,
                        "should":
                        [
                            {
                                "match":
                                {
                                    "nameData.displayName":
                                    {
                                        "fuzziness": "AUTO",
                                        "query": "Blue chip"
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "from": 0,
    "size": 20,
    "sort":
    [
        "_score"
    ]
}
```
Getting results with 'nameData.displayName' as  follows
```
"nameData.displayName": "JM Value",
"nameData.displayName": "ITI Value Fund",
"nameData.displayName": "Axis Value Fund",
```

Verified that its the 'fuzziness' causing this. When i remove it or set it to '1' it's working fine.
Zinc is searching for individual tokens but using the fuzziness of the entire query.
Hence 'Blue' is becoming 'Value'  since we are allowing edit distance of '2' based on the query length. 

Expectation
'AUTO' Fuzziness should be decided based on the token length rather than the query length

**Which service(s) is this relate to?**
Search API

**Comment by hengfeiyang** [comment]
I will check it later

**Comment by hengfeiyang** [comment]
@ayush71994 fixed, it will release in next version.
