### ISSUE TITLE
Sort values on Elasticsearch API

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zinc#405]
**Is your feature request related to a problem? Please describe.**
One of the most important needs on Search clusters is to be **Sorted** by the user's choice. 
As zinc supports sorting by a value, I considered that it'll accept on the **ES API** but as I see the documentation there was no support on it. Most of zinc's users are probably from a Elasticsearch's context and using client like olivere.
Will this feature be released for ease of use and compatibility?

**Comment by hengfeiyang** [comment]
Actually we support basic sort on ES search API. but not description in our documents, you can have a try.

we supports:

```json
{
  "sort": [
    {"field":"asc"},
    {"field2": "desc"},
    {"field3": {"order": "asc"}},
    {"field4": {"order": "desc"}}
  ]
}
```

**Comment by amirEBD** [comment]
Thanks indeed @hengfeiyang, 
That is correct actually. Another question I have is why there is an **empty error** field when responding to queries which have no errors? 
This will cause my client _olivere_, encountered errors.

Example:
`{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0
    },
    "max_score": 0,
    "hits": []
  },
  "error": ""
}`

**Comment by hengfeiyang** [comment]
As we design `error` field is a string type. i will test your client. What client library do you use?

**Comment by amirEBD** [comment]
[Olivere](https://github.com/olivere/elastic)

**Comment by amirEBD** [comment]
Indeed there is no problem with your design, but ES won't return an empty error field in the response.
[ES Doc Example](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/search-search.html#search-search-api-example)

**Comment by hengfeiyang** [comment]
@amirEBD Can give me a example of Olivere, i will test it with branch: https://github.com/zinclabs/zinc/tree/fix-search-response-error

Or you can test it too.

**Comment by amirEBD** [comment]
Thanks for your quick responding,
Yes it is ok now :))))))))
WIll it be merged as soon as possible? We need this PR for production testing. @hengfeiyang
