### ISSUE TITLE
bufio.Scanner: token too long

### ISSUE THREAD

**Issue by pashangshangpo** [zinclabs/zinc#413]
When using /api/_bulk, when a field of a single document exceeds a certain size, it will report { error: 'bufio.Scanner: token too long' } This error, how big can a single field be? No instructions were found in the documentation.

I want to store a piece of json content, about a few MB, what should I do in this case?

**Comment by prabhatsharma** [comment]
Each line can be maximum of 1 MB at this time which is pretty big in general. What are you trying to store?

**Comment by pashangshangpo** [comment]
> Each line/document can be maximum of 1 MB at this time which is pretty big in general. What are you trying to store?

I have a file resource search program, which stores the current directory name, as well as all file names and paths in the current directory. The directory level is very deep. It is stored in a keyword field without index. When searching for a file name At the time, I want to display all the file directories under this file name directory in my search result interface. Because the directory level is very deep, the files are very large, but I want to store data. What should I do in this situation? Can the user set the default size by himself?

**Comment by pashangshangpo** [comment]
@prabhatsharma

**Comment by prabhatsharma** [comment]
Currently the size of each document is hardcoded in Zinc. at 1 MB. I will make it configurable so you can change it.

**Comment by prabhatsharma** [comment]
https://github.com/zinclabs/zinc/pull/426

**Comment by prabhatsharma** [comment]
It will be part of the next release. You can set environment variable ZINC_MAX_DOCUMENT_SIZE=1048576 (1 MB) or more accordingly.

You can find dev release [binaries](http://zincsearch-releases.s3-website-us-west-2.amazonaws.com/dev#dev/0.2.9-9c0a5d9-dev-2022-08-12T01:50:42Z/) and pull the container from public.ecr.aws/zinclabs/zinc-dev:0.2.9-9c0a5d9-dev

**Comment by timetravel-1010** [comment]
> It will be part of the next release. You can set environment variable ZINC_MAX_DOCUMENT_SIZE=1048576 (1 MB) or more accordingly.
> 
> You can find dev release [binaries](http://zincsearch-releases.s3-website-us-west-2.amazonaws.com/dev#dev/0.2.9-9c0a5d9-dev-2022-08-12T01:50:42Z/) and pull the container from public.ecr.aws/zinclabs/zinc-dev:0.2.9-9c0a5d9-dev

That env variable is still missing in the documentation, but it already works. Thanks.
