### ISSUE TITLE
Search after API to get the next results

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zinc#420]
**Is your feature request related to a problem? Please describe.**
As all search engines primary need, pagination is a crucial important feature. Cause not to send all founded results to clients.
As elasticsearch has mentioned it [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html) there is a pagination scrolling inside ES.
Does zinc support it? (As my knowledge no :) ) Whether there is another way to paginate?

**Comment by hengfeiyang** [comment]
I know that, for now we just supported use `from` and `size` to paginate data. We need a better solution.

**Comment by amirEBD** [comment]
Thanks indeed,
If I want to collaborate on the project to acheive this goal, could you help me as start to code on your code base? Or any useful explanation for that?

**Comment by dxfcrddd** [comment]
http://localhost:4080/es/web/_search

param:

{"query":{"multi_match":{"query":"video,","type":"cross_fields","operator":"and","fields":["tags"]}},"size":10,"from":10}


expect 10  but return 20 

why?       0.2.6version

**Comment by hengfeiyang** [comment]
@dxfcrddd https://github.com/zinclabs/zinc/pull/464 fixed.
