### ISSUE TITLE
Mini Dashboard Feature

### ISSUE THREAD

**Issue by Avey777** [zinclabs/zinc#427]
![image](https://user-images.githubusercontent.com/35259040/184277649-515d086c-c275-49e3-b69c-597f151a0363.png)
![image](https://user-images.githubusercontent.com/35259040/184277859-f43373e8-6167-4791-9db2-cd1351a17f6b.png)
是否可以默认提供类似的UI Demo ，以便于更清晰的给我们的业务人员推荐Znic ；都知道漂亮的东西，更加容易说服 出钱的那个人，看起来更加高级和有品位

**Comment by hengfeiyang** [comment]
Good idea! I hope somebody can contribute it for Zinc.

**Comment by Nike682631** [comment]
@hengfeiyang I'll try to contribute it but can you please translate it for me?

**Comment by hengfeiyang** [comment]
@Nike682631 , @Avey777 Means, if we can provide a minimal UI for full text search demo. like the images above. 

In the UI, it has a search box in the head area, and have a result list, it can paginate. 

Just the shows that, zinc can used for product search or something else.

But i think, this demo UI should as a third-party project, not in zinc main project.

**Comment by hengfeiyang** [comment]
@Avey777 Can you provide more information, the screenshot looks other search project demo UI.

**Comment by Nike682631** [comment]
@hengfeiyang  Can you assign me this issue? Also if I don't have to commit it to main zinc project please lemme know how I need to proceed with it.

**Comment by prabhatsharma** [comment]
@Nike682631 You can simply fork the project and create a pull request.

**Comment by Avey777** [comment]
It‘s Meilisearch and Algolia.
Meilisearch: https://github.com/meilisearch/meilisearch
Algolia: https://www.algolia.com

上面的两个搜索系统我们都有在使用，并且我们愿意为之付费。 但是zinc 在我们看来 未来可能会适合我们的内部的分布式搜索(如果后续增加了AI  会更好) ，我们一直在尝试更轻量更面向未来的搜索系统。 但是我们自己并不开发搜索系统，我们只是寻找更好的搜索系统 并使用它。 我们并不喜欢es ，虽然我们当前还在内部的日志搜索上使用他。 我们正在寻求的替代es的方案。 但是我们的Boss 喜欢漂亮的东西，Boos 认为漂亮代表实力；关于这点我们无法改变。 这也是我们选择meilisearch和Algolia的主要原因。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Hengfei ***@***.***>
发送时间: 2022年8月14日 9:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [zinclabs/zinc] Mini Dashboard Feature (Issue #427)


@Avey777<https://github.com/Avey777> Can you provide more information, the screenshot looks other search project demo UI.

―

**Comment by Avey777** [comment]
> @Nike682631 , @Avey777 Means, if we can provide a minimal UI for full text search demo. like the images above.
> 
> In the UI, it has a search box in the head area, and have a result list, it can paginate.
> 
> Just the shows that, zinc can used for product search or something else.
> 
> But i think, this demo UI should as a third-party project, not in zinc main project.

I think this UI page should be added to the main project of zinc, both ALgoia and Meilisearch do this
