### ISSUE TITLE
Searching for a single Slash (`/`) fails

### ISSUE THREAD

**Issue by Thomas-Ganter** [zinclabs/zinc#430]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

I want to find records that have a field (`path`) containing a single slash (`/`) character. 

**What action did you take?**

I tried `path:/`, `path:\/`, `path:"/"` and many more things I could think of and would expect are valid ways to escape a single slash, but all these methods failed. 

**What action/response/output did you expect?**

I get a filtered result set containing the searched-for records. 

**What actually happened?**

I get a brief error popup at the bottom of the screen and the slash character gets highlighted in all previously displayed (not newly fetched) documents. See screenshot below.  

**How to reproduce the issue?**

Create a document containing a field with a single slash and search for it. 

**What version of ZincSearch are you using?**

Latest commit as of two days ago (197486c3a48c9906e0fe69aae3118594ac5ff7d9). 

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

Not that I can think of. 

**Any attachments/screenshots?**
![ZINC path search error](https://user-images.githubusercontent.com/877147/184298458-83d80b73-7ad3-49ed-a4d8-5b74d32db902.png)

**Which service(s) is this relate to?**
GUI **and** API  
(I also tried a python script going through all query scenarios I can think of)

**Comment by hengfeiyang** [comment]
You should follow steps:

1. set an environment variable `ZINC_ENABLE_TEXT_KEYWORD_MAPPING=true`
2. reindex data
3. in UI, we not provide complex query, you can query it use API  https://docs.zincsearch.com/api-es-compatible/search/search/
4. use term query for the field you want:

```
{
	"query": {
		"bool": {
			"must": [
				{
					"term": {
						"path.keyword":"/"
					}
				}
			]
		}
}
```

`path` is the field.

**Comment by Thomas-Ganter** [comment]
> * reindex data

What do you mean by _reindex data_ ?? — I have millions of records in there. 
Is all the ingestion broken that I did?

**Comment by Thomas-Ganter** [comment]
> * set an environment variable `ZINC_ENABLE_TEXT_KEYWORD_MAPPING=true`

And what exactly would that environment variable change in terms of behaviour?
Will it change anything else (i. e. what are the side effects)?

**Comment by hengfeiyang** [comment]
This config for: https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html#text-multi-fields
Enable this config, we will add a keyword type field named `name.keyword`, and ingest the field as multiple field.

1. text field for FullText search.
2. keyword field for term query.

So, you ingested data before enable this config, there is no `name.keyword` field, so it not support query a single character like `/`, this query just can do query on keyword field.

**Comment by Thomas-Ganter** [comment]
Thanks for the explanation.  
Can I retroactively apply this to the existing indices, or is this only working going forward?

**Comment by hengfeiyang** [comment]
Just effect new documents. Because old documents have indexed, will not be changed.

**Comment by Thomas-Ganter** [comment]
The above solution works. 
Thanks!

And re. _reindexing_ — thankfully I had written a migration script a while back when the Index format changed, so I am just now migrating from old into new index, one document at a time, so it takes a while but it works…
