### ISSUE TITLE
Template endpoints won't work

### ISSUE THREAD

**Issue by amirEBD** [zinclabs/zinc#439]
**What were you trying to achieve?**
I'm am trying to get `http://localhost:4080/es/_index_template` to make a template index in Zinc but all I get is: 
`{"error":"template.name should be not empty"}`

PS.: I copied the example in this [page](https://docs.zincsearch.com/api-es-compatible/index/create-template/)

**Comment by hengfeiyang** [comment]
Confirm, we will fix it, and before that you can set the param `target` let it work:

```
POST /es/_index_template/:target
```

**Comment by amirEBD** [comment]
As I tested the built template, the problem with creating the template was solved but it doesn't work.
Create template: 
```
POST /es/_index_template

{
  "name": "t2",
  "index_patterns": [
    "game-*"
  ],
  "priority": 100,
  "template": {
    "settings": {
      "analysis": {
        "analyzer": {
          "default": {
            "type": "standard"
          }
        }
      }
    },
    "mappings": {
      "properties": {
        "content": {
          "type": "text",
          "index": true,
          "store": true,
          "sortable": false,
          "aggregatable": false,
          "highlightable": true
        }
      }
    }
  }
}
```

Create index: 
```
POST /api/index

{
  "name": "game-1",
  "storage_type": "disk",
  "shard_num": 1
}
```

As I get the mappings it'll return this:
```
{
  "game-1": {
    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "_id": {
          "type": "keyword"
        }
      }
    }
  }
}
```

**Comment by hengfeiyang** [comment]
Sorry, you can use `PUT /es/_index_template` instead of `POST`, it will be can work. We have already fixed, will release in next version.

**Comment by amirEBD** [comment]
I've built the latest version of zinc myself as you fixed the issue by 14ea0671ee931e1c75679df4a8ca04a06c6da134 commit.
The problem is template functionality is not working as I tested.

**Comment by hengfeiyang** [comment]
Thank you for report, i will fix it.

**Comment by hengfeiyang** [comment]
@amirEBD you can have a try with the latest code of main branch.

**Comment by amirEBD** [comment]
I had tested it but bugs hadn't been fixed. Again tested with [this](https://github.com/zinclabs/zinc/issues/439#issuecomment-1217856090) templates. Settings and mappings are empty.

**Comment by hengfeiyang** [comment]
Maybe you should clear you data directory, pull latest code, go build, and do it again. i tested it should be fixed.

**Comment by prabhatsharma** [comment]
@amirEBD How are you testing it? It works pretty well in our tests on main branch. Can you clear your data folder and try again.

**Comment by amirEBD** [comment]
Sorry for answering late a bit,
I had cleared my data directory and tested this imput data as I said [here](https://github.com/zinclabs/zinc/issues/439#issuecomment-1217856090)
I want to see the `settings` set by the template but it doesn't appear. Can you achieve the `settings` of `game-1` index?

**Comment by hengfeiyang** [comment]
Thanks, i fixed settings with template.

**Comment by amirEBD** [comment]
Thanks, I have tested and it worked fine both on settings and mappings :)))
