### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by dimgsg9** [zinclabs/zinc#44]
Would be lovely to have "how to contribute" section, a way to gain insights into your backlog and/or any working group meet up(s). So we can quickly identify opportunities to render our assistance.

Happy to get involved ~ 10hrs/week (go/vuejs)

**Comment by prabhatsharma** [comment]
Totally. Thanks a lot. I will soon add contributing guidelines and documentation on how to get started in this area.

**Comment by prabhatsharma** [comment]
I have added contributing guide at https://github.com/prabhatsharma/zinc/blob/main/CONTRIBUTING.md . I tried to detail a lot of stuff for getting started with development. Let me know if something is missing and could help.

**Comment by dimgsg9** [comment]
Thank you @prabhatsharma , it's a great start.
Having some basic scrum board or a list of backlog items labeled with priorities (based on your initial opinion) would be helpful too... let me know if we should fork this discussion into separate issue

**Comment by prabhatsharma** [comment]
thanks for your POV. I have been wanting to have a public roadmap as github projects. Still crystallizing certain things. Will do it soon.

**Comment by prabhatsharma** [comment]
@dimgsg9  we have a public roadmap available now. Let us know what you think.

**Comment by prabhatsharma** [comment]
Closing as we have good enough info on how to get started with contributing. Feel free to reopen if something is missing.
