### ISSUE TITLE
In the image that deploys the latest Zinc, the corresponding field label does not display metadata

### ISSUE THREAD

**Issue by YibiaoWu** [zinclabs/zinc#447]
Note: Any issue that does not follow below template will be closed without consideration. You may remove this line when filing issue.

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Display corresponding data through fields

**What action did you take?**
Check the corresponding field label
![image](https://user-images.githubusercontent.com/92915249/186054294-aa2ce7c2-7ac8-4857-a731-dc9fb362b81e.png)

**What action/response/output did you expect?**
Display the corresponding field metadata information,But not showing yet
![image](https://user-images.githubusercontent.com/92915249/186054722-475faa45-9e76-469a-b265-b28e24c1bff7.png)

**What actually happened?**
![image](https://user-images.githubusercontent.com/92915249/186054821-9a4e0da7-1565-4750-8463-d3a328f2e922.png)

**How to reproduce the issue?**

**What version of ZincSearch are you using?**
latest mirror version
]# kubectl get  sts zinc -owide
NAME   READY   AGE   CONTAINERS   IMAGES
zinc   1/1     18m   zinc         public.ecr.aws/zinclabs/zinc:latest

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
The log did not report any errors during the query process
![image](https://user-images.githubusercontent.com/92915249/186055266-fef28d1e-6f43-44cf-9c77-a7863a9dcaf2.png)

**Any attachments/screenshots?**

**Which service(s) is this relate to?**
This could be GUI or API

**Comment by prabhatsharma** [comment]
fixed in https://github.com/zinclabs/zinc/pull/449

**Comment by prabhatsharma** [comment]
You can use public.ecr.aws/zinclabs/zinc-dev:0.2.10-338b741-dev or http://zincsearch-releases.s3-website-us-west-2.amazonaws.com/dev#dev/0.2.10-338b741-dev-2022-08-23T10:09:39Z/

**Comment by YibiaoWu** [comment]
> 您可以使用 public.ecr.aws/zinclabs/zinc-dev:0.2.10-338b741-dev 或[http://zincsearch-releases.s3-website-us-west-2.amazonaws.com/dev#dev/0.2 .10-338b741-dev-2022-08-23T10:09:39Z/](http://zincsearch-releases.s3-website-us-west-2.amazonaws.com/dev#dev/0.2.10-338b741-dev-2022-08-23T10:09:39Z/)
I tested this image without problems, Thank you!
