### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by 291237388** [zinclabs/zinc#448]
When I try to create document by /api/test/_multi，i find fatal error: runtime: out of memory ,the log like this
![11111](https://user-images.githubusercontent.com/24401624/186062810-db0c58e0-c558-4da7-aaa6-36af9af58424.jpg)

**Comment by hengfeiyang** [comment]
How many documents do you ingest, and How many memory do you give zinc, in docker?

**Comment by hengfeiyang** [comment]
And can you post the runtime stack?

**Comment by 291237388** [comment]
My server  is 4-core/8G, I give memory to zinc by default
Here is my docker commod
docker run -itd -v /home/zinc/data:/data -e ZINC_DATA_PATH="/data" -p 4080:4080 \
    -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=123456 \
    -e ZINC_PLUGIN_GSE_ENABLE=true \
    -e ZINC_MAX_DOCUMENT_SIZE=524288000 \
    --name zinc

**Comment by prabhatsharma** [comment]
Its probably due to the very high document size. What is the size of your HTTP _bulk request and what is the size of each document in the request?

**Comment by 291237388** [comment]
yeah,I try to foreach my local document file like word、excel、ppt into zinc, it may be has so many documents and _bulk request about 200 documnets(10M total)  each.

**Comment by prabhatsharma** [comment]
Try reducing ZINC_MAX_DOCUMENT_SIZE=524288000 if you can. This should help.

**Comment by 291237388** [comment]
I haved reducing ZINC_MAX_DOCUMENT_SIZE, But I have a large document file with  about 150m,It is still out of memory,here is a log and runtime stack.
![2222](https://user-images.githubusercontent.com/24401624/186356057-c72a9298-884a-483f-9f35-fbdf090c49a3.jpg)
![333333](https://user-images.githubusercontent.com/24401624/186356131-cec93123-6f8b-43eb-8809-5deda52d083f.jpg)

**Comment by hengfeiyang** [comment]
I'm not sure about this case. i am so sad. 😞

you have a file of 150MB, it is a word format, pdf or plain text file?

**Comment by 291237388** [comment]
most of  xlsx format

**Comment by hengfeiyang** [comment]
Thanks for report, It looks zinc not suitable for you case.
