### ISSUE TITLE
Plain text password is storing to local storage

### ISSUE THREAD

**Issue by chetannn** [zinclabs/zinc#451]
Storing plain text password would be critical. I don't know if this is intentional or not but user basic info and token will be fine.

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/22125423/186312313-e4e090d0-8f20-4fe1-b683-f852d32f125f.png">

**Comment by chetannn** [comment]
I think the issue is fixed. I am closing the issue.

**Comment by saharshtapi** [comment]
@hengfeiyang how do I install this fixed version???

**Comment by hengfeiyang** [comment]
Wait we make new release, or you can use nightly version. https://docs.zincsearch.com/releases/#binary-releases
