### ISSUE TITLE
Invalid Credentials - Login bug

### ISSUE THREAD

**Issue by jpastorm** [zinclabs/zinc#458]
Hello, I am trying to enter zinc but I have not been able to from my linux operating system, download the version release **`zinc_0.3.0_Linux_x86_64.tar.gz`** and run it as the documentation says **`ZINC_FIRST_ADMIN_USER=admin ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123 ./zinc`** but always it gives me invalid credentials

**Comment by hengfeiyang** [comment]
Please check you input:

user:   `admin`
pass:  `Complexpass#123`

Or, Maybe there have some logs output?

**Comment by jpastorm** [comment]
`{"level":"info","method":"POST","code":200,"took":0,"time":"2022-08-25T09:48:10-05:00","message":"/api/login"}`

This is the log with code 200, even though I put the credentials correctly, the frontend tells me invalid credentials

**Comment by hengfeiyang** [comment]
Maybe you have old data, you can try delete data directory:

```
rm -fR data
```

Then, run zinc again.

**Comment by jpastorm** [comment]
thanks, That worked
