### ISSUE TITLE
Change chartKeyFormat for FullTime to fix Histogram in web UI

### ISSUE THREAD

**Issue by iNtEgraIR2021** [zinclabs/zinc#466]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**

1. searching a huge dataset of > 3.000.000 records using the web user interface
2. reading the **histogram** chart

**What action did you take?**

*please see above*

**What action/response/output did you expect?**

Labels of histogram chart given in a useful format -> not *HH:MM:SS* (please see [`chartKeyFormat`](https://github.com/zinclabs/zinc/blob/ff82a77057311819a3b3174302e0cfad9520f32c/web/src/components/search/SearchResult.vue#L309) in source code)

**What actually happened?**

![image](https://user-images.githubusercontent.com/80395360/186897918-0e46f499-fcc7-4034-8ad8-eb0ac388fbb0.png)

**How to reproduce the issue?**

*please see above*

The root cause (to my personal understanding) is the lack of an aggregation witch triggers the following [console output](https://github.com/zinclabs/zinc/blob/ff82a77057311819a3b3174302e0cfad9520f32c/web/src/components/search/SearchResult.vue#L461): *'res.data.aggregations is null'*

The following selection of a suiting datetime format being skipped leads (based on my understanding of the source code) to the bug described above.

**What version of ZincSearch are you using?**

```
Version 0.2.9
Build 0
CommitHash 6c66ceec7600ff8660374d33ca692a015780c7f5
Branch 0
BuildDate 2022-08-21T15:25:21Z
```

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**

Please consider adding `hits.hits.total.value` as a criterion for the selection of the datetime format in [`SearchResult.vue`](https://github.com/zinclabs/zinc/blob/ff82a77057311819a3b3174302e0cfad9520f32c/web/src/components/search/SearchResult.vue#L338).

*Why?* Well please see the following screenshot:
![image](https://user-images.githubusercontent.com/80395360/186900279-5f671485-5fa9-4558-8d21-ec9af33301c3.png)

When searching with a date range a high number of results might lead to a vertical overflow in the UI and bad readability in general.

Using angled labels for the x axis might improve the readability.[^1]

**Any attachments/screenshots?**

The issue is caused by the number (➡️  and thereby the `interval` (*1M*) in `aggregations.histogram`) of results **not** by searching with 'FullTime' range:

![image](https://user-images.githubusercontent.com/80395360/186899059-20a0208d-cfa0-4f01-8836-e26aa9bacffa.png)

**Which service(s) is this related to?**

GUI

[^1]: please also see: https://github.com/apexcharts/apexcharts.js/issues/446 and https://apexcharts.com/javascript-chart-demos/column-charts/column-with-rotated-xaxis-labels/

**Comment by hengfeiyang** [comment]
Thanks, i will check it.

**Comment by prabhatsharma** [comment]
We will be migrating to plotly from apexchart in due course of time. We will avoid putting effort on this for now.
