### ISSUE TITLE
Query suggestions API feasibility

### ISSUE THREAD

**Issue by koltyakov** [zinclabs/zinc#476]
Hello! It's more a question about technical feasibility and plans for implementing query suggestions API rather than requesting this feature.

**Is your feature request related to a problem? Please describe.**
Currently no. Yet, suggestions are pretty common requirements in many search applications.

**Describe the solution you'd like**
Implement query suggestions API (something like https://www.elastic.co/guide/en/app-search/current/query-suggestion.html)

**Describe alternatives you've considered**
`--`

**Additional context**
It's common to expect quick search suggestions, when search API returns a possible values based on already entered query text.

**Comment by prabhatsharma** [comment]
Not on the roadmap yet but definitely possible. Essentially we will need to make a search for partial queries for specific fields and return the most common results.

**Comment by koltyakov** [comment]
Thanks for the answer! It would be a great feature to have someday in future. Glad to hear you assume it as a something technically possible.
