### ISSUE TITLE
 .NET Client: Unable to verify that the server is Elasticsearch

### ISSUE THREAD

**Issue by jwillmer** [zinclabs/zinc#502]
**What were you trying to achieve?**
Replacing elasticsearch with zinc.

**What action did you take?**
Deploying zinc and updating connection string of our application to point to zinc instead of elasticsearch.

**What action/response/output did you expect?**
No exceptions. Everything works as before.

**What actually happened?**
Application throws exception and dies:
```
Error: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
```

**How to reproduce the issue?**
Install [.NET elasticcearch client](https://github.com/elastic/elasticsearch-net) version 7.14.1 and configure elasticsearch:
```
var settings = new ConnectionSettings(new Uri(url))
                .BasicAuthentication(configuration["Elasticsearch:user"], configuration["Elasticsearch:password"])
                .DefaultIndex(defaultIndex)
                .DefaultMappingFor<AssembledPage>(m => m);

 var client = new ElasticClient(settings);
```

**What version of ZincSearch are you using?**
0.3.1

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
Problematic code:

```
public void HealthCheck(WaitForStatus waitForStatus = WaitForStatus.Yellow)
{
    var response = _elasticClient.Cluster.Health(new ClusterHealthRequest() { WaitForStatus = waitForStatus, Timeout = 3000 });
    var healthColor = response.Status.ToString().ToLower();

    if (response.IsValid)
    {
        // ...
    }
    else
    {
        var message = "Error: " + response.ApiCall.OriginalException.Message;
        Console.WriteLine(message);
        throw new Exception(message);
    }
}
```

**Which service(s) is this relate to?**
API

**Comment by jergoo** [comment]
@jwillmer there is a ProductCheck in [.NET elasticcearch client](https://github.com/elastic/elasticsearch-net) version 7.14.1, you can check the `src/Electicsearch.NET/Transport/Pipeline/RequestPipeline.cs`, it sends a `GET /` request to the server and applies some rules to the response info to make sure the node is good to use, the response of ES is like this:
```
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json
content-encoding: gzip
content-length: 324

{
  "name": "891b1935f0d2",
  "cluster_name": "docker-cluster",
  "cluster_uuid": "lKUtmkOtSaq82ucXmRgbwA",
  "version": {
    "number": "8.2.0",
    "build_flavor": "default",
    "build_type": "docker",
    "build_hash": "b174af62e8dd9f4ac4d25875e9381ffe2b9282c5",
    "build_date": "2022-04-20T10:35:10.180408517Z",
    "build_snapshot": false,
    "lucene_version": "9.1.0",
    "minimum_wire_compatibility_version": "7.17.0",
    "minimum_index_compatibility_version": "7.0.0"
  },
  "tagline": "You Know, for Search"
}
```

while you won't get this kind of response from zinc server, such as the version info and the X-elastic-product header, so the ProductCheck won't pass. Maybe you should try to update your client version, I don't see the same ProductCheck action in the new client, or wait for zinc to make some compatibility support.

**Comment by jwillmer** [comment]
I removed the `IsValid` check and only process the state based on the health color:

```
var healthColor = response.Status.ToString().ToLower();
```
