### ISSUE TITLE
ZINC_DATA_PATH is not writable

### ISSUE THREAD

**Issue by jwillmer** [zinclabs/zinc#512]
**What were you trying to achieve?**
Running the docker image

**What action did you take?**
Running stock example with mapped valume path returns error. Same is true if I don't specify any volume mount.
```
docker run -v /root/docker/zincsearch:/data -e DATA_PATH="/data" -p 4080:4080 \
    -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123 \
    --name zinc public.ecr.aws/h9e2j3o7/zinc:latest
```

**What action/response/output did you expect?**
Running app

**What actually happened?**
```
{"level":"debug","time":"2022-09-06T14:44:50Z","message":"open .env: no such file or directory"}
{"level":"fatal","error":"mkdir data/_test_: permission denied","time":"2022-09-06T14:44:50Z","message":"ZINC_DATA_PATH is not writable"}

```

**How to reproduce the issue?**
Just start it

**What version of ZincSearch are you using?**
I tried with latest and 0.3.1

**Anything else that you can tell that will help us diagnose and resolve the issue efficiently?**
I am running a ubuntu server.

**Comment by prabhatsharma** [comment]
can you try:

> chmod a+rwx /root/docker/zincsearch

**Comment by tymonx** [comment]
This is caused by wrong `user:group` between the directory from the host machine `/root/docker/zincsearch` that assume is `root:root` and from container that is `appuser:appuser` set in the Zinc [Dockerfile](https://github.com/zinclabs/zinc/blob/main/Dockerfile#L75).

To solve this, overwrite the Zinc image user with the `--user root` Docker run argument:

```plaintext
docker run --user root -v /root/docker/zincsearch:/data -e DATA_PATH="/data" -p 4080:4080 \
    -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123 \
    --name zinc public.ecr.aws/h9e2j3o7/zinc:latest
```

If you are also planning using Zin in Docker Compose use `user: root`. It also work for named volumes. For volumes with host path as source `--volume <host-path>:<container-path>` in OS with SElinx add `:rw,z` at the end of the volume option `--volume <host-path>:<container-path>:rw,z`.

**Comment by jwillmer** [comment]
Ok, great, thank you for the workaround. But I think you should fix this. You can't use a user without root and then break the deployment / require workarounds for it. I uploaded a gist on how we prevent this from happening in our images. Please have a look and see if it is any use for you: [Create image without root user and folder access ](https://gist.github.com/jwillmer/9eef7a4922ff8d32583f913481e5a53e)

**Comment by tymonx** [comment]
I agree with @jwillmer (sorry but I'm not a Zinc contributor only humble Zinc user).

Zinc team should create and add default directory with ownership for `appuser:appuser` and set the `DATA_PATH` environment variable on default to this value. This should work with host source and also named volumes.

**Comment by jwillmer** [comment]
As I said event this does not work
![image](https://user-images.githubusercontent.com/1503577/188900261-180f17f9-57ab-484a-b5f4-c4817a3f3ddc.png)

**Comment by hengfeiyang** [comment]
@jwillmer, Thanks, i will fix it.

**Comment by tymonx** [comment]
@hengfeiyang I have created a proper Pull Request that will fix this https://github.com/zinclabs/zinc/pull/516

```plaintext
docker volume create zinc

docker run -v zinc:/var/lib/zinc -p 4080:4080 \
    -e ZINC_FIRST_ADMIN_USER=admin -e ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123 \
    --name zinc zinc
```

I can also create Pull Request for Zinc documentation to encourage people to use named volumes rather that host source paths.
