### ISSUE TITLE
Helm chart: use headless service for statefulSet's serviceName

### ISSUE THREAD

**Issue by babykart** [zinclabs/zinc#522]
Hi,

First, thanks you for this project! 

**What were you trying to achieve?**

Installing zinc via Helm chart.

**What action did you take?**

`helm install zinc helm/zinc -n zinc`

**What action/response/output did you expect?**

According to the kubernetes documentation (https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations), the _statefulSet_ should use a headless service for its _serviceName_.

**What actually happened?**

The _statefulSet_ of the helm chart actually uses a classic _ClusterIP_ service as _serviceName_.

Let me now if you need a PR.

**Comment by prabhatsharma** [comment]
Makes sense. Happy to get a PR on this.
