### ISSUE TITLE
zinc name is conflict with zinc compiler for Scala

### ISSUE THREAD

**Issue by shaba** [zinclabs/zinc#53]
Please see
https://github.com/sbt/zinc

**Comment by prabhatsharma** [comment]
Am open to name change. Any alternate name suggestions?

**Comment by iredmail** [comment]
`GoSearch` 😄

**Comment by prabhatsharma** [comment]
Let's keep the suggestions coming

**Comment by shaba** [comment]
sorry, my fantasy is bad :)
- recollected
- mnemosina(Spanish) or mnemozina(Romanian) name of Mnemosyne (https://en.wikipedia.org/wiki/Mnemosyne). Mnemosyne name is already taken.

**Comment by prabhatsharma** [comment]
I like both memozina and memosyne. Let's sleep on it for a while.

**Comment by iredmail** [comment]
IMO Better use English word(s) instead of Spanish / Romanian.

**Comment by fcarvalhido** [comment]
Quaerere => Search in Latin

**Comment by HeCorr** [comment]
I honestly really like the name Zinc. It's easy to pronounce and remember  ;)

**Comment by prabhatsharma** [comment]
I think we are keeping the name ZincSearch. A lot of people I have talked to to really like the simplicity.
