### ISSUE TITLE
ZincSearch UI showing full log when selected index field is NOT present in log

### ISSUE THREAD

**Issue by h121h** [zinclabs/zinc#618]
When using the ZincSearch UI, and selecting an index field that does NOT exists in some logs, it shows the full log.

**What action/response/output did you expect?**
The UI not to show anything as the index field doesn't exists (blank).

**What actually happened?**
Any log where an index field is NOT present, and select in the UI, the UI shows the full log, instead of just showing blank.

**How to reproduce the issue?**
Log in to UI.
Select an index.
Select a few index fields.
Any log where that a selected index field is NOT present, it shows the full log. Previous versions the UI wouldn't show anything (blank). Which I believe is the expected behavior.

**What version of ZincSearch are you using?**
0.3.3

**Which service(s) is this relate to?**
User Interface - GUI

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiaojun207** [comment]
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/10277455/198639016-732b7303-04df-4ab5-ac20-3dd5065cbdd0.png">

Yes, This problem does exist. I will revise it later
