### ISSUE TITLE
opensearch support ?

### ISSUE THREAD

**Issue by gedw99** [zinclabs/zinc#65]
https://github.com/opensearch-project/opensearch-go is an elastic alternaitve.

Seems perfect match ?

**Comment by prabhatsharma** [comment]
@gedw99 Its not really an elasticsearch alternative. Its just  go sdk / opensearch go client for opensearch. Are you looking to use it with zinc?

**Comment by gedw99** [comment]
hey @prabhatsharma yes i just was brainstorming that opensearch-go and zinc would work well together.

**Comment by gedw99** [comment]
"opensearch-go is [a community-driven, open source fork](https://aws.amazon.com/blogs/opensource/introducing-opensearch/) of go-elasticsearch" So it coudl act as a client for zinc

**Comment by gedw99** [comment]
https://github.com/opensearch-project/opensearch-cli coudl act as a CLI also.

**Comment by prabhatsharma** [comment]
Totally. We are working towards API compatibility. This might work soon the
the most part.

**Comment by gedw99** [comment]
@prabhatsharma see the opensearch integration with benthos. Its the first PR.

https://github.com/benthosdev/benthos/pull/1388

Would be nice if Zinc worked with this...

**Comment by prabhatsharma** [comment]
@gedw99 Can you elaborate on what is it that you mean by opensearch support?

**Comment by gedw99** [comment]
Or sure what’s missing but that repo allows devs to use be this with the open search api .

if you know benthos then you can appreciate how useful this is for integrating zinc with other systems without any compilation stage
