### ISSUE TITLE
Swagger test not working in non-local environment

### ISSUE THREAD

**Issue by Mashull** [zinclabs/zinc#676]
When we deploy zinc at dev env, swagger's host is also 'localhost'.

![image](https://user-images.githubusercontent.com/118787336/204092443-7efe1377-6731-4bc7-9a82-2d40d47d2f9a.png)

**Comment by Mashull** [comment]
The 'host' configuration is may be unnecessary.

![image](https://user-images.githubusercontent.com/118787336/204092474-a844be99-46ad-4939-b3b6-3c42566e78f1.png)

**Comment by hengfeiyang** [comment]
It looks like you are right. can you create a PR for this? thanks.

**Comment by hengfeiyang** [comment]
fixed
