### ISSUE TITLE
rest api always no auth.

### ISSUE THREAD

**Issue by fangaofeng** [zinclabs/zinc#693]
**What were you trying to achieve?**
http://127.0.0.1:4080/swagger/index.html#/Index/ListIndexes
already Available authorizations.
**What action did you take?**
get /api/index

**What action/response/output did you expect?**
get result
**What actually happened?**
![1672125478779](https://user-images.githubusercontent.com/15919475/209627379-f29584d0-503b-4ce0-a142-3d738bd79fb6.png)
**What version of ZincSearch are you using?**
version of ZincSearch: 0.35

**Comment by coader** [comment]
also got this error , already login but still show missing credentials
