### ISSUE TITLE
support get  /index/_doc/:id  ?

### ISSUE THREAD

**Issue by fangaofeng** [zinclabs/zinc#694]
Retrieves the specified JSON document from an index.
for example
GET my-index-000001/_doc/0
return id is 0‘s json document.

**Comment by hengfeiyang** [comment]
for now, we have no this API. if many users need it, we will add it.

**Comment by fangaofeng** [comment]
if get document id, then can get document. 
zinc can be storage db , not need other relation db.

**Comment by hengfeiyang** [comment]
i know that, just only you ask for this feature.  if many users need it, we will add it.

**Comment by gedw99** [comment]
This is useful for me. So +1.

my use case is that I can then use zinc as a cache of the documents that are indexed by zinc, so that clients can request the actually document . Hope that is well described .

**Comment by hengfeiyang** [comment]
fixed

**Comment by fangaofeng** [comment]
thanks, i try it！

**Comment by fangaofeng** [comment]
test this api:
![1676362816687](https://user-images.githubusercontent.com/15919475/218678759-d4e00d6b-7f9f-4add-993d-f584a10042e1.png)
red rectangle should not required document in body.
![1676362907459](https://user-images.githubusercontent.com/15919475/218679076-d6bd180e-bcda-408e-b6db-7c5eb7d130f1.png)
