### ISSUE TITLE
bulk index data format error

### ISSUE THREAD

**Issue by remram44** [zinclabs/zinc#752]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**What were you trying to achieve?**
Try out zinc

**What action did you take?**
- Grabbed 0.3.6 release for Linux x86_64
- Opened the [quickstart page](https://docs.zinc.dev/quickstart/)
- Ran zinc with `ZINC_FIRST_ADMIN_USER=admin ZINC_FIRST_ADMIN_PASSWORD=admin ./zinc`
- Created a file with a single document `doc.json`: `{"id": "31268", "body": "data here idk"}`
- Posted it with curl: `curl http://localhost:4080/api/_bulk -i -u admin:admin --data-binary @doc.json`

**What action/response/output did you expect?**
Ingest works like in quickstart guide

**What actually happened?**
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Zinc: 0.3.6
Date: Sat, 11 Feb 2023 03:05:26 GMT
Content-Length: 40

{"error":"bulk index data format error"}
```

**What version of ZincSearch are you using?**
[0.3.6 for Linux x86_64](https://github.com/zinclabs/zinc/releases/download/v0.3.6/zinc_0.3.6_Linux_x86_64.tar.gz)

**Which service(s) is this relate to?**
API

**Comment by hengfeiyang** [comment]
You can follow the document API:
https://docs.zinc.dev/api/document/bulk/
https://docs.zinc.dev/api/document/bulkv2/
https://docs.zinc.dev/api/document/mutli/

**Comment by remram44** [comment]
Sorry, I am trying out too many search libraries today and I read a little fast. Massaging my jsonl file into this format lets me import my documents, sorry again about the noise!
