### ISSUE TITLE
How to send logs from nginx to zinc in docker?

### ISSUE THREAD

**Issue by devig** [zinclabs/zinc#82]
Could you add some examples to send logs from nginx?

**Comment by devig** [comment]
@hengfeiyang thank you.
fluent-bit - config does not work's for me. And as I know syslog-rfc3164 used UDP, UDP - may loose data.
I think rsyslog (with TCP) may be better. 

How I can read logs from stdout if I am using docker?

**Comment by hengfeiyang** [comment]
the config file of fluent-bit just an example, and the syslog just a defined parser.

fluent-bit has some components: input, parser, filter, output.

no matter, let me know how is you use nginx with docker? i'll guide you.

1. run nginx, zinc as single container in a hosted docker (centos, ubuntu, macos).
2. run nginx, zinc as a deployment in k8s cluster.
