### ISSUE TITLE
Question: does zinc provide elasticsearch-compatible API?

### ISSUE THREAD

**Issue by cibolog** [zinclabs/zinc#9]
I would like to use Magento 2 open source ecommerce platform, which requires elasticsearch as a prerequisite for the installation. Would it be possible to swap ES with zinc?

Thank you in advance!

**Comment by HeCorr** [comment]
From the readme:

```
It is a drop-in replacement for elasticsearch if you are just ingesting data using APIs (...)
```

So I imagine it would be but you'd have to try it out to make sure

**Comment by HeCorr** [comment]
I believe I misinterpreted it. Apparently only the ingest API is compatible, the search API is not.

**Comment by mklueh** [comment]
Would be great to have elasticsearch API compatibility to allow using with Hibernate Search. I think this would help a lot of people. Are there any plans to make the API compatible in future?

**Comment by hengfeiyang** [comment]
zinc has compatible most es query dsl in version v0.1.7, you can have a try.

**Comment by prabhatsharma** [comment]
Closing this as we have a lot of search APIs now compatible with ES. Feel free to create an issue if there is a need for a specific API.

**Comment by Hades32** [comment]
@prabhatsharma is there a full compatibility table available? I didn't find anything at https://docs.zincsearch.com/api-es-compatible/search/search/ . BTW, I had to search for this issue, because the readme isn't really clear about the status of the search API compatibility either
