### ISSUE TITLE
update-document API documentation is incomplete

### ISSUE THREAD

**Issue by ivan-redooc** [zinclabs/zinc#97]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Which service(s) is this relate to?**
[The update-document API](https://docs.zincsearch.io/API%20Reference/update-document/#request)

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard or not doable?**
I'm trying to update a record just created following the documentation, but instead I got a new record.

### Create a record: ###
```SH
$ curl  --trace-ascii /dev/stdout  -H 'Content-Type: application/json'  -H "Accept: application/json"  -XPUT -u utente:chiave  \
http://localhost:4080/api/test/document -d '{"sequence":"1","value":"two"}'
```

### Update a record: ###
```SH
$ curl  --trace-ascii /dev/stdout  -H 'Content-Type: application/json'  -H "Accept: application/json"  -XPUT -u utente:chiave  \
http://localhost:4080/api/test/document -d '{"sequence":"1","value":"one"}'
```

**Are you currently working around this issue?**
Passing the `_id` field to the requests.

### Create a record: ###
```SH
$ curl  --trace-ascii /dev/stdout  -H 'Content-Type: application/json'  -H "Accept: application/json"  -XPUT -u utente:chiave  \
http://localhost:4080/api/test/document -d '{"_id":"sequence-1","sequence":"1","value":"two"}'
```

### Update a record: ###
```SH
$ curl  --trace-ascii /dev/stdout  -H 'Content-Type: application/json'  -H "Accept: application/json"  -XPUT -u utente:chiave  \
http://localhost:4080/api/test/document -d '{"_id":"sequence-1","sequence":"1","value":"one"}'
```

**Additional context**
The documentation page do not refer to the "_id" at all:

> <h1 id="updatedocument">UpdateDocument</h1>
> <p>Create/Update a document and index it for searches</p>
> <p>Endpoint - PUT /api/:target/document</p>
> <p>Create/Update a document and index it for searches</p>
> <h2 id="request">Request</h2>
> <p>e.g. 
> PUT http://localhost:4080/api/myindex/document</p>
> <p>Request Body: 
> </p><div class="highlight"><pre id="__code_1"><span></span><button class="md-clipboard md-icon" title="Copy to clipboard" data-clipboard-target="#__code_1 > code"></button><code><a id="__codelineno-0-1" name="__codelineno-0-1" href="#__codelineno-0-1"></a><span class="p">{</span><span class="w"> </span>
> <a id="__codelineno-0-2" name="__codelineno-0-2" href="#__codelineno-0-2"></a><span class="w">    </span><span class="nt">"name"</span><span class="p">:</span><span class="w"> </span><span class="s2">"Prabhat Sharma"</span><span class="w"> </span>
> <a id="__codelineno-0-3" name="__codelineno-0-3" href="#__codelineno-0-3"></a><span class="p">}</span><span class="w"></span>
> </code></pre></div><p></p>

I think the docs should clarify how to correctly update a document.

**Comment by hengfeiyang** [comment]
Documents updated. you can follow this: https://docs.zincsearch.com/api/document/update-with-id/
